name: Build many-layers
on:
  workflow_dispatch:
  push:
    branches: ["master"]
    paths:
      - .github/workflows/build-deploy.yml
      - .github/workflows/many-layers.yml
      - many-layers/**
jobs:
  build:
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/build-deploy.yml
    with:
      image: many-layers
    secrets: inherit
