name: Build php-fpm
on:
  workflow_dispatch:
  push:
    branches: ["master"]
    paths:
      - .github/workflows/build-deploy.yml
      - .github/workflows/php-fpm.yml
      - php-fpm/**
jobs:
  build:
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/build-deploy.yml
    with:
      image: php-fpm
    secrets: inherit
