name: Build php-fpm
on:
  push:
    branches: ["master"]
jobs:
  build:
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/build-deploy.yml
    with:
      image: php-fpm
    secrets: inherit
