name: Build smtp-telegram
on:
  push:
    branches: ["master"]
jobs:
  build:
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/build-deploy.yml
    with:
      image: smtp-telegram
    secrets: inherit
